spring:
  application:
    name: relay-processor
  
  datasource:
    url: jdbc:postgresql://localhost:5432/iotdb
    username: iotuser
    password: iotpass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    streams:
      application-id: relay-processor
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde

logging:
  level:
    com.supermetrics.relay: INFO
    org.springframework.kafka: WARN
    org.apache.kafka.streams: INFO

